name: Test My Go Action

on:
  workflow_dispatch:
  
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run My Custom Go Action
        uses: ./
        with:
          name: "custom-action"
          version: 1.0.1
          url: "ghcr.io/srimanpadmanabancb/gha-action/custom-action:latest"
          digest: "test"
          type: "docker"
          cloudbees-url: ${{ vars.CBP_PREPROD_URL }}
          cloudbees-pat: ${{ secrets.CBP_GHA_PAT }}
