name: Test My Go Action for many tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run-go-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: kubernetes/kubernetes
      - name: Run Tests with Maven
        run: |
          go test ./... | tee ./test.log
          cat ./test.log | go-junit-report >./test.xml
          ls -lrt
      # - name: Run My Custom Go Action for GO
      #   uses: cloudbees-gha-cbp/publish-test-results@main
      #   with:
      #     test-type: JUNIT
      #     folder-path: target/surefire-reports/*
      #     cloudbees-url: ${{ secrets.CBP_PREPROD_URL }}
      #     cloudbees-pat: ${{ secrets.CBP_GHA_PAT }}
